name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io 
  IMAGE_NAME: admin-cv  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Necesario para GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}  # Para GHCR (usa secrets para Docker Hub)
          password: ${{ secrets.GITHUB_TOKEN }}  # Token automático de GitHub

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}  # Solo push en master
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
